-- ============================================================================
-- seed.sql — Configuración inicial de los tenants (GENERADO automáticamente
-- desde src/seeds/ por scripts/genSeedSql.mjs). No editar a mano.
-- Ejecutar en Supabase DESPUÉS de 001/002/003. Idempotente (on conflict do nothing).
-- ============================================================================


-- ===== Tenant: Convenio Asociación Guajira (Ecopetrol–Hocol) 2026 (ten-hocol) =====
insert into public.tenants (id, nombre, financiador, entidad_ejecutora, unidad_analisis_default, moneda, vigencia_inicio, vigencia_fin, estado, config) values ('ten-hocol', 'Convenio Asociación Guajira (Ecopetrol–Hocol) 2026', 'Hocol S.A.', 'Fundación Guajira Competitiva', 'comunidad', 'COP', '2026-01-01', '2027-04-30', 'activo', '{"roles_nombres":{"gestor":"Gestor Comunitario Wayuu","coordinador":"Coordinador Territorial","director":"Director del Proyecto","admin_fin":"Profesional Administrativo y Financiero","admin_tenant":"Administrador de Tenant","financiador":"Hocol S.A. (consulta)","auditor":"Auditor (consulta)"},"pqrs_niveles":[{"nivel":"verde","sla_horas":72,"responsables":["gestor"],"descripcion":"Informativa / inconformidad aislada"},{"nivel":"amarillo","sla_horas":48,"responsables":["coordinador"],"descripcion":"Inconformidad recurrente / tensión localizada"},{"nivel":"naranja","sla_horas":24,"responsables":["coordinador","director"],"descripcion":"Conflicto activo / riesgo de bloqueo"},{"nivel":"rojo","sla_horas":0,"responsables":["director","coordinador"],"descripcion":"Riesgo a vida/integridad, VBG, bloqueo crítico (atención inmediata)"}],"idiomas":["es","way"],"consentimiento":{"finalidad":"Registro y seguimiento de beneficiarios del convenio de inversión social Asociación Guajira (Ecopetrol–Hocol), con enfoque étnico y conforme a la Ley 1581 de 2012. Los datos se usan exclusivamente para los fines del convenio.","medios":["fisico","digital","verbal_testificado"]}}'::jsonb) on conflict (id) do nothing;
-- program_lines (6)
insert into public.program_lines (id, tenant_id, codigo, nombre, tipo, orden, fases) values ('line-hocol-l1', 'ten-hocol', 'L1', 'L1 — Fortalecimiento comunitario', 'estructurada', 1, '[{"orden":1,"nombre":"Diagnóstico"},{"orden":2,"nombre":"Caracterización"},{"orden":3,"nombre":"Plan de fortalecimiento"},{"orden":4,"nombre":"Formulación de proyectos"},{"orden":5,"nombre":"Implementación y planes de inversión"},{"orden":6,"nombre":"Sostenibilidad"}]'::jsonb) on conflict (id) do nothing;
insert into public.program_lines (id, tenant_id, codigo, nombre, tipo, orden, fases) values ('line-hocol-l2', 'ten-hocol', 'L2', 'L2 — Atención de solicitudes', 'flexible', 2, '[]'::jsonb) on conflict (id) do nothing;
insert into public.program_lines (id, tenant_id, codigo, nombre, tipo, orden, fases) values ('line-hocol-l3', 'ten-hocol', 'L3', 'L3 — Cultura y patrimonio', 'flexible', 3, '[]'::jsonb) on conflict (id) do nothing;
insert into public.program_lines (id, tenant_id, codigo, nombre, tipo, orden, fases) values ('line-hocol-l4', 'ten-hocol', 'L4', 'L4 — Apoyos humanitarios y usos y costumbres', 'flexible', 4, '[]'::jsonb) on conflict (id) do nothing;
insert into public.program_lines (id, tenant_id, codigo, nombre, tipo, orden, fases) values ('line-hocol-l5', 'ten-hocol', 'L5', 'L5 — Salud', 'flexible', 5, '[]'::jsonb) on conflict (id) do nothing;
insert into public.program_lines (id, tenant_id, codigo, nombre, tipo, orden, fases) values ('line-hocol-meal', 'ten-hocol', 'MEAL', 'Eje transversal MEAL', 'transversal', 6, '[]'::jsonb) on conflict (id) do nothing;
-- units (36)
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-01', 'ten-hocol', 'Comunidad Wayuu 01 — Riohacha (nombre por confirmar en onboarding)', 'riohacha', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-02', 'ten-hocol', 'Comunidad Wayuu 02 — Riohacha (nombre por confirmar en onboarding)', 'riohacha', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-03', 'ten-hocol', 'Comunidad Wayuu 03 — Riohacha (nombre por confirmar en onboarding)', 'riohacha', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-04', 'ten-hocol', 'Comunidad Wayuu 04 — Riohacha (nombre por confirmar en onboarding)', 'riohacha', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-05', 'ten-hocol', 'Comunidad Wayuu 05 — Riohacha (nombre por confirmar en onboarding)', 'riohacha', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-06', 'ten-hocol', 'Comunidad Wayuu 06 — Riohacha (nombre por confirmar en onboarding)', 'riohacha', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-07', 'ten-hocol', 'Comunidad Wayuu 07 — Riohacha (nombre por confirmar en onboarding)', 'riohacha', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-08', 'ten-hocol', 'Comunidad Wayuu 08 — Riohacha (nombre por confirmar en onboarding)', 'riohacha', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-09', 'ten-hocol', 'Comunidad Wayuu 09 — Riohacha (nombre por confirmar en onboarding)', 'riohacha', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-10', 'ten-hocol', 'Comunidad Wayuu 10 — Riohacha (nombre por confirmar en onboarding)', 'riohacha', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-11', 'ten-hocol', 'Comunidad Wayuu 11 — Riohacha (nombre por confirmar en onboarding)', 'riohacha', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-12', 'ten-hocol', 'Comunidad Wayuu 12 — Riohacha (nombre por confirmar en onboarding)', 'riohacha', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-13', 'ten-hocol', 'Comunidad Wayuu 13 — Riohacha (nombre por confirmar en onboarding)', 'riohacha', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-14', 'ten-hocol', 'Comunidad Wayuu 14 — Riohacha (nombre por confirmar en onboarding)', 'riohacha', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-15', 'ten-hocol', 'Comunidad Wayuu 15 — Riohacha (nombre por confirmar en onboarding)', 'riohacha', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-16', 'ten-hocol', 'Comunidad Wayuu 16 — Riohacha (nombre por confirmar en onboarding)', 'riohacha', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-17', 'ten-hocol', 'Comunidad Wayuu 17 — Riohacha (nombre por confirmar en onboarding)', 'riohacha', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-18', 'ten-hocol', 'Comunidad Wayuu 18 — Riohacha (nombre por confirmar en onboarding)', 'riohacha', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-19', 'ten-hocol', 'Comunidad Wayuu 19 — Manaure (nombre por confirmar en onboarding)', 'manaure', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-20', 'ten-hocol', 'Comunidad Wayuu 20 — Manaure (nombre por confirmar en onboarding)', 'manaure', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-21', 'ten-hocol', 'Comunidad Wayuu 21 — Manaure (nombre por confirmar en onboarding)', 'manaure', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-22', 'ten-hocol', 'Comunidad Wayuu 22 — Manaure (nombre por confirmar en onboarding)', 'manaure', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-23', 'ten-hocol', 'Comunidad Wayuu 23 — Manaure (nombre por confirmar en onboarding)', 'manaure', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-24', 'ten-hocol', 'Comunidad Wayuu 24 — Manaure (nombre por confirmar en onboarding)', 'manaure', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-25', 'ten-hocol', 'Comunidad Wayuu 25 — Manaure (nombre por confirmar en onboarding)', 'manaure', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-26', 'ten-hocol', 'Comunidad Wayuu 26 — Manaure (nombre por confirmar en onboarding)', 'manaure', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-27', 'ten-hocol', 'Comunidad Wayuu 27 — Manaure (nombre por confirmar en onboarding)', 'manaure', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-28', 'ten-hocol', 'Comunidad Wayuu 28 — Manaure (nombre por confirmar en onboarding)', 'manaure', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-29', 'ten-hocol', 'Comunidad Wayuu 29 — Manaure (nombre por confirmar en onboarding)', 'manaure', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-30', 'ten-hocol', 'Comunidad Wayuu 30 — Manaure (nombre por confirmar en onboarding)', 'manaure', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-31', 'ten-hocol', 'Comunidad Wayuu 31 — Manaure (nombre por confirmar en onboarding)', 'manaure', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-32', 'ten-hocol', 'Comunidad Wayuu 32 — Manaure (nombre por confirmar en onboarding)', 'manaure', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-33', 'ten-hocol', 'Comunidad Wayuu 33 — Manaure (nombre por confirmar en onboarding)', 'manaure', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-34', 'ten-hocol', 'Comunidad Wayuu 34 — Manaure (nombre por confirmar en onboarding)', 'manaure', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-35', 'ten-hocol', 'Comunidad Wayuu 35 — Manaure (nombre por confirmar en onboarding)', 'manaure', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-36', 'ten-hocol', 'Comunidad Wayuu 36 — Manaure (nombre por confirmar en onboarding)', 'manaure', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
-- indicators (44)
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-001', 'ten-hocol', NULL, NULL, NULL, 'IND-EST-01', 'Comunidades fortalecidas', 'Comunidades', NULL, 36, 0, 'numero', 'final', 'Actas de cierre de fase por comunidad', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-002', 'ten-hocol', NULL, NULL, NULL, 'IND-EST-02', 'Proyectos comunitarios formulados', 'Proyectos', NULL, 36, 0, 'numero', 'trimestral', 'Documentos de proyecto formulados', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-003', 'ten-hocol', NULL, NULL, NULL, 'IND-EST-03', 'Proyectos comunitarios implementados', 'Proyectos', NULL, 36, 0, 'numero', 'trimestral', 'Actas de entrega e informes de implementación', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-004', 'ten-hocol', NULL, NULL, NULL, 'IND-EST-04', 'Cumplimiento físico del convenio', '%', NULL, 95, 0, 'porcentaje', 'mensual', 'Tablero de control — avance físico', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-005', 'ten-hocol', NULL, NULL, NULL, 'IND-EST-05', 'Ejecución financiera del convenio', '%', NULL, 95, 0, 'porcentaje', 'mensual', 'Informe financiero mensual', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-006', 'ten-hocol', NULL, NULL, NULL, 'IND-EST-06', 'Cumplimiento de cronograma', '%', NULL, 95, 0, 'porcentaje', 'mensual', 'Cronograma actualizado vs ejecutado', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-007', 'ten-hocol', NULL, NULL, NULL, 'IND-EST-07', 'Trazabilidad documental', '%', NULL, 100, 0, 'porcentaje', 'continua', 'Repositorio documental con evidencias enlazadas', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-008', 'ten-hocol', NULL, NULL, NULL, 'IND-EST-08', 'Satisfacción del financiador', '%', NULL, 90, 0, 'porcentaje', 'semestral', 'Encuesta de satisfacción Hocol', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-009', 'ten-hocol', NULL, NULL, 'line-hocol-l1', 'IND-L1-01', 'Diagnósticos comunitarios realizados', 'Diagnósticos', NULL, 36, 0, 'numero', 'mensual', 'Fichas de diagnóstico validadas', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-010', 'ten-hocol', NULL, NULL, 'line-hocol-l1', 'IND-L1-02', 'Comunidades caracterizadas', 'Comunidades', NULL, 36, 0, 'numero', 'mensual', 'Fichas de caracterización validadas', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-011', 'ten-hocol', NULL, NULL, 'line-hocol-l1', 'IND-L1-03', 'Planes de fortalecimiento elaborados', 'Planes', NULL, 36, 0, 'numero', 'trimestral', 'Planes de fortalecimiento aprobados', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-012', 'ten-hocol', NULL, NULL, 'line-hocol-l1', 'IND-L1-04', 'Proyectos formulados (L1)', 'Proyectos', NULL, 36, 0, 'numero', 'trimestral', 'Documentos de formulación', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-013', 'ten-hocol', NULL, NULL, 'line-hocol-l1', 'IND-L1-05', 'Proyectos implementados (L1)', 'Proyectos', NULL, 36, 0, 'numero', 'trimestral', 'Actas de implementación', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-014', 'ten-hocol', NULL, NULL, 'line-hocol-l1', 'IND-L1-06', 'Planes de inversión ejecutados', 'Planes', NULL, 36, 0, 'numero', 'trimestral', 'Soportes de ejecución de inversión', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-015', 'ten-hocol', NULL, NULL, 'line-hocol-l1', 'IND-L1-07', 'Culminación de procesos de formación', '%', NULL, 90, 0, 'porcentaje', 'trimestral', 'Registros de asistencia y certificados', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-016', 'ten-hocol', NULL, NULL, 'line-hocol-l1', 'IND-L1-08', 'Estrategia de sostenibilidad formulada', 'Documento', NULL, 1, 0, 'numero', 'final', 'Documento de estrategia aprobado', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-017', 'ten-hocol', NULL, NULL, 'line-hocol-l2', 'IND-L2-01', 'Solicitudes atendidas', 'Solicitudes', NULL, NULL, 0, 'numero', 'mensual', 'Registros de solicitud con cierre técnico', NULL, NULL, false, true, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-018', 'ten-hocol', NULL, NULL, 'line-hocol-l2', 'IND-L2-02', 'Solicitudes con cierre técnico', '%', NULL, 100, 0, 'porcentaje', 'mensual', 'Actas de cierre técnico', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-019', 'ten-hocol', NULL, NULL, 'line-hocol-l2', 'IND-L2-03', 'Solicitudes atendidas en tiempo', '%', NULL, 90, 0, 'porcentaje', 'mensual', 'Comparativo fecha solicitud vs atención', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-020', 'ten-hocol', NULL, NULL, 'line-hocol-l2', 'IND-L2-04', 'Trazabilidad de solicitudes', '%', NULL, 100, 0, 'porcentaje', 'continua', 'Expedientes con evidencias completas', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-021', 'ten-hocol', NULL, NULL, 'line-hocol-l3', 'IND-L3-01', 'Iniciativas culturales apoyadas', 'Iniciativas', NULL, NULL, 0, 'numero', 'trimestral', 'Registros de apoyo cultural', NULL, NULL, false, true, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-022', 'ten-hocol', NULL, NULL, 'line-hocol-l3', 'IND-L3-02', 'Actividades de patrimonio realizadas', 'Actividades', NULL, NULL, 0, 'numero', 'trimestral', 'Registros de actividad con evidencia', NULL, NULL, false, true, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-023', 'ten-hocol', NULL, NULL, 'line-hocol-l3', 'IND-L3-03', 'Participantes en actividades culturales', 'Personas', NULL, NULL, 0, 'numero', 'trimestral', 'Registros de asistencia', NULL, NULL, false, true, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-024', 'ten-hocol', NULL, NULL, 'line-hocol-l3', 'IND-L3-04', 'Satisfacción con actividades culturales', '%', NULL, 90, 0, 'porcentaje', 'semestral', 'Encuestas de satisfacción', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-025', 'ten-hocol', NULL, NULL, 'line-hocol-l4', 'IND-L4-01', 'Apoyos humanitarios ejecutados', 'Apoyos', NULL, NULL, 0, 'numero', 'mensual', 'Registros de apoyo con acta de entrega', NULL, NULL, false, true, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-026', 'ten-hocol', NULL, NULL, 'line-hocol-l4', 'IND-L4-02', 'Atenciones de usos y costumbres', 'Atenciones', NULL, NULL, 0, 'numero', 'mensual', 'Registros de atención', NULL, NULL, false, true, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-027', 'ten-hocol', NULL, NULL, 'line-hocol-l4', 'IND-L4-03', 'Trazabilidad de apoyos (L4)', '%', NULL, 100, 0, 'porcentaje', 'continua', 'Expedientes con evidencias completas', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-028', 'ten-hocol', NULL, NULL, 'line-hocol-l4', 'IND-L4-04', 'Satisfacción con apoyos (L4)', '%', NULL, 90, 0, 'porcentaje', 'semestral', 'Encuestas de satisfacción', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-029', 'ten-hocol', NULL, NULL, 'line-hocol-l5', 'IND-L5-01', 'Jornadas y acciones de salud realizadas', 'Jornadas', NULL, NULL, 0, 'numero', 'mensual', 'Registros de atención en salud', NULL, NULL, false, true, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-030', 'ten-hocol', NULL, NULL, 'line-hocol-l5', 'IND-L5-02', 'Personas beneficiadas en salud', 'Personas', NULL, NULL, 0, 'numero', 'mensual', 'Registros de atención individual', NULL, NULL, false, true, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-031', 'ten-hocol', NULL, NULL, 'line-hocol-l5', 'IND-L5-03', 'Instituciones de salud articuladas', 'Instituciones', NULL, NULL, 0, 'numero', 'trimestral', 'Convenios/actas de articulación', NULL, NULL, false, true, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-032', 'ten-hocol', NULL, NULL, 'line-hocol-l5', 'IND-L5-04', 'Satisfacción con jornadas de salud', '%', NULL, 90, 0, 'porcentaje', 'semestral', 'Encuestas de satisfacción', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-033', 'ten-hocol', NULL, NULL, 'line-hocol-meal', 'IND-MEAL-01', 'Línea base consolidada', 'Documento', NULL, 1, 0, 'numero', 'final', 'Documento de línea base congelado', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-034', 'ten-hocol', NULL, NULL, 'line-hocol-meal', 'IND-MEAL-02', 'Sistema MEAL en operación', 'Sistema', NULL, 1, 0, 'numero', 'continua', 'Plataforma operativa con usuarios activos', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-035', 'ten-hocol', NULL, NULL, 'line-hocol-meal', 'IND-MEAL-03', 'Tablero de control actualizado mensualmente', '%', NULL, 100, 0, 'porcentaje', 'mensual', 'Bitácora de actualización del tablero', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-036', 'ten-hocol', NULL, NULL, 'line-hocol-meal', 'IND-MEAL-04', 'Indicadores actualizados al día', '%', NULL, 100, 0, 'porcentaje', 'mensual', 'Reporte de vigencia de indicadores', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-037', 'ten-hocol', NULL, NULL, 'line-hocol-meal', 'IND-MEAL-05', 'Informes técnicos mensuales entregados', 'Informes', NULL, 12, 0, 'numero', 'mensual', 'Informes técnicos radicados', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-038', 'ten-hocol', NULL, NULL, 'line-hocol-meal', 'IND-MEAL-06', 'Informes financieros mensuales entregados', 'Informes', NULL, 12, 0, 'numero', 'mensual', 'Informes financieros radicados', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-039', 'ten-hocol', NULL, NULL, 'line-hocol-meal', 'IND-MEAL-07', 'Informes de seguimiento entregados', 'Informes', NULL, 12, 0, 'numero', 'mensual', 'Informes de seguimiento radicados', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-040', 'ten-hocol', NULL, NULL, 'line-hocol-meal', 'IND-MEAL-08', 'Evaluación final realizada', 'Evaluación', NULL, 1, 0, 'numero', 'final', 'Informe de evaluación final', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-041', 'ten-hocol', NULL, NULL, 'line-hocol-meal', 'IND-MEAL-09', 'Evaluación de impacto realizada', 'Evaluación', NULL, 1, 0, 'numero', 'final', 'Informe de evaluación de impacto', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-042', 'ten-hocol', NULL, NULL, 'line-hocol-meal', 'IND-MEAL-10', 'Documento de lecciones aprendidas', 'Documento', NULL, 1, 0, 'numero', 'final', 'Documento consolidado de lecciones', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-043', 'ten-hocol', NULL, NULL, 'line-hocol-meal', 'IND-MEAL-11', 'Banco de evidencias consolidado', 'Repositorio', NULL, 1, 0, 'numero', 'continua', 'Repositorio documental completo', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-044', 'ten-hocol', NULL, NULL, 'line-hocol-meal', 'IND-MEAL-12', 'Trazabilidad extremo a extremo', '%', NULL, 100, 0, 'porcentaje', 'continua', 'Auditoría de reconstrucción de indicadores', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
-- forms (9)
insert into public.forms (id, tenant_id, codigo, nombre, version, linea_id, activo, campos) values ('frm-hocol-lineabase', 'ten-hocol', 'F-LB', 'Encuesta de línea base comunitaria', 1, 'line-hocol-l1', true, '[{"name":"comunidad_confirma","etiqueta_es":"Comunidad donde se aplica","etiqueta_way":null,"tipo":"texto","obligatorio":true,"reglas_validacion":null},{"name":"fecha_aplicacion","etiqueta_es":"Fecha de aplicación","etiqueta_way":null,"tipo":"fecha","obligatorio":true,"reglas_validacion":null},{"name":"geopunto","etiqueta_es":"Ubicación de la aplicación","etiqueta_way":null,"tipo":"geo","obligatorio":true,"reglas_validacion":null},{"name":"poblacion_total","etiqueta_es":"Población total estimada de la comunidad","etiqueta_way":null,"tipo":"num","obligatorio":true,"reglas_validacion":null},{"name":"familias","etiqueta_es":"Número de familias","etiqueta_way":null,"tipo":"num","obligatorio":true,"reglas_validacion":null},{"name":"acceso_agua","etiqueta_es":"¿La comunidad cuenta con acceso a agua?","etiqueta_way":null,"tipo":"bool","obligatorio":true,"reglas_validacion":null},{"name":"fuente_ingresos","etiqueta_es":"Principal fuente de ingresos","etiqueta_way":null,"tipo":"select","obligatorio":true,"reglas_validacion":null,"opciones":["Pastoreo","Artesanías","Pesca","Comercio","Jornaleo","Otra"]},{"name":"observaciones","etiqueta_es":"Observaciones generales","etiqueta_way":null,"tipo":"texto","obligatorio":false,"reglas_validacion":null}]'::jsonb) on conflict (id) do nothing;
insert into public.forms (id, tenant_id, codigo, nombre, version, linea_id, activo, campos) values ('frm-hocol-caracterizacion', 'ten-hocol', 'F-CAR', 'Ficha de caracterización comunitaria', 1, 'line-hocol-l1', true, '[{"name":"autoridad","etiqueta_es":"Autoridad tradicional de la comunidad","etiqueta_way":null,"tipo":"texto","obligatorio":true,"reglas_validacion":null},{"name":"estado_reconocimiento","etiqueta_es":"Estado de reconocimiento","etiqueta_way":null,"tipo":"select","obligatorio":true,"reglas_validacion":null,"opciones":["Legalizada","En proceso"]},{"name":"geopunto","etiqueta_es":"Coordenadas de la comunidad","etiqueta_way":null,"tipo":"geo","obligatorio":true,"reglas_validacion":null},{"name":"foto_panoramica","etiqueta_es":"Foto panorámica de la comunidad","etiqueta_way":null,"tipo":"foto","obligatorio":true,"reglas_validacion":null},{"name":"organizaciones","etiqueta_es":"Organizaciones presentes en la comunidad","etiqueta_way":null,"tipo":"texto","obligatorio":false,"reglas_validacion":null}]'::jsonb) on conflict (id) do nothing;
insert into public.forms (id, tenant_id, codigo, nombre, version, linea_id, activo, campos) values ('frm-hocol-asistencia', 'ten-hocol', 'F-ASI', 'Registro de asistencia', 1, 'line-hocol-l1', true, '[{"name":"actividad","etiqueta_es":"Nombre de la actividad","etiqueta_way":null,"tipo":"texto","obligatorio":true,"reglas_validacion":null},{"name":"fecha","etiqueta_es":"Fecha de la actividad","etiqueta_way":null,"tipo":"fecha","obligatorio":true,"reglas_validacion":null},{"name":"num_asistentes","etiqueta_es":"Número de asistentes","etiqueta_way":null,"tipo":"num","obligatorio":true,"reglas_validacion":null},{"name":"num_mujeres","etiqueta_es":"Número de mujeres asistentes","etiqueta_way":null,"tipo":"num","obligatorio":true,"reglas_validacion":null},{"name":"foto_asistencia","etiqueta_es":"Foto del listado de asistencia","etiqueta_way":null,"tipo":"foto","obligatorio":true,"reglas_validacion":null},{"name":"firma_responsable","etiqueta_es":"Firma del responsable","etiqueta_way":null,"tipo":"firma","obligatorio":true,"reglas_validacion":null}]'::jsonb) on conflict (id) do nothing;
insert into public.forms (id, tenant_id, codigo, nombre, version, linea_id, activo, campos) values ('frm-hocol-acta-entrega', 'ten-hocol', 'F-ACT', 'Acta de entrega', 1, 'line-hocol-l1', true, '[{"name":"bien_entregado","etiqueta_es":"Bien o servicio entregado","etiqueta_way":null,"tipo":"texto","obligatorio":true,"reglas_validacion":null},{"name":"receptor","etiqueta_es":"Persona/organización que recibe","etiqueta_way":null,"tipo":"texto","obligatorio":true,"reglas_validacion":null},{"name":"fecha_entrega","etiqueta_es":"Fecha de entrega","etiqueta_way":null,"tipo":"fecha","obligatorio":true,"reglas_validacion":null},{"name":"geopunto","etiqueta_es":"Lugar de la entrega","etiqueta_way":null,"tipo":"geo","obligatorio":true,"reglas_validacion":null},{"name":"foto_entrega","etiqueta_es":"Registro fotográfico de la entrega","etiqueta_way":null,"tipo":"foto","obligatorio":true,"reglas_validacion":null},{"name":"firma_receptor","etiqueta_es":"Firma de quien recibe","etiqueta_way":null,"tipo":"firma","obligatorio":true,"reglas_validacion":null}]'::jsonb) on conflict (id) do nothing;
insert into public.forms (id, tenant_id, codigo, nombre, version, linea_id, activo, campos) values ('frm-hocol-solicitud', 'ten-hocol', 'F-SOL', 'Registro de solicitud (L2)', 1, 'line-hocol-l2', true, '[{"name":"descripcion","etiqueta_es":"Descripción de la solicitud","etiqueta_way":null,"tipo":"texto","obligatorio":true,"reglas_validacion":null},{"name":"fecha_solicitud","etiqueta_es":"Fecha de la solicitud","etiqueta_way":null,"tipo":"fecha","obligatorio":true,"reglas_validacion":null},{"name":"solicitante","etiqueta_es":"Nombre del solicitante o autoridad","etiqueta_way":null,"tipo":"texto","obligatorio":true,"reglas_validacion":null},{"name":"priorizada","etiqueta_es":"¿Priorizada por el financiador?","etiqueta_way":null,"tipo":"bool","obligatorio":true,"reglas_validacion":null},{"name":"estado_atencion","etiqueta_es":"Estado de atención","etiqueta_way":null,"tipo":"select","obligatorio":true,"reglas_validacion":null,"opciones":["Registrada","En gestión","Atendida","Cerrada"]}]'::jsonb) on conflict (id) do nothing;
insert into public.forms (id, tenant_id, codigo, nombre, version, linea_id, activo, campos) values ('frm-hocol-apoyo-cultural', 'ten-hocol', 'F-CUL', 'Registro de apoyo cultural (L3)', 1, 'line-hocol-l3', true, '[{"name":"iniciativa","etiqueta_es":"Iniciativa o actividad cultural apoyada","etiqueta_way":null,"tipo":"texto","obligatorio":true,"reglas_validacion":null},{"name":"fecha","etiqueta_es":"Fecha de la actividad","etiqueta_way":null,"tipo":"fecha","obligatorio":true,"reglas_validacion":null},{"name":"participantes","etiqueta_es":"Número de participantes","etiqueta_way":null,"tipo":"num","obligatorio":true,"reglas_validacion":null},{"name":"foto_actividad","etiqueta_es":"Registro fotográfico","etiqueta_way":null,"tipo":"foto","obligatorio":true,"reglas_validacion":null},{"name":"satisfaccion","etiqueta_es":"Satisfacción de los participantes (1 a 5)","etiqueta_way":null,"tipo":"escala","obligatorio":true,"reglas_validacion":null}]'::jsonb) on conflict (id) do nothing;
insert into public.forms (id, tenant_id, codigo, nombre, version, linea_id, activo, campos) values ('frm-hocol-apoyo-humanitario', 'ten-hocol', 'F-HUM', 'Registro de apoyo humanitario (L4)', 1, 'line-hocol-l4', true, '[{"name":"tipo_apoyo","etiqueta_es":"Tipo de apoyo","etiqueta_way":null,"tipo":"select","obligatorio":true,"reglas_validacion":null,"opciones":["Humanitario","Usos y costumbres"]},{"name":"descripcion","etiqueta_es":"Descripción del apoyo entregado","etiqueta_way":null,"tipo":"texto","obligatorio":true,"reglas_validacion":null},{"name":"fecha_entrega","etiqueta_es":"Fecha de entrega","etiqueta_way":null,"tipo":"fecha","obligatorio":true,"reglas_validacion":null},{"name":"geopunto","etiqueta_es":"Lugar de entrega","etiqueta_way":null,"tipo":"geo","obligatorio":true,"reglas_validacion":null},{"name":"foto_entrega","etiqueta_es":"Registro fotográfico","etiqueta_way":null,"tipo":"foto","obligatorio":true,"reglas_validacion":null},{"name":"firma_receptor","etiqueta_es":"Firma de quien recibe","etiqueta_way":null,"tipo":"firma","obligatorio":true,"reglas_validacion":null}]'::jsonb) on conflict (id) do nothing;
insert into public.forms (id, tenant_id, codigo, nombre, version, linea_id, activo, campos) values ('frm-hocol-atencion-salud', 'ten-hocol', 'F-SAL', 'Registro de atención en salud (L5)', 1, 'line-hocol-l5', true, '[{"name":"tipo_jornada","etiqueta_es":"Tipo de jornada o acción de salud","etiqueta_way":null,"tipo":"texto","obligatorio":true,"reglas_validacion":null},{"name":"fecha","etiqueta_es":"Fecha de la jornada","etiqueta_way":null,"tipo":"fecha","obligatorio":true,"reglas_validacion":null},{"name":"personas_atendidas","etiqueta_es":"Personas atendidas","etiqueta_way":null,"tipo":"num","obligatorio":true,"reglas_validacion":null},{"name":"institucion","etiqueta_es":"Institución de salud articulada","etiqueta_way":null,"tipo":"texto","obligatorio":false,"reglas_validacion":null},{"name":"foto_jornada","etiqueta_es":"Registro fotográfico","etiqueta_way":null,"tipo":"foto","obligatorio":true,"reglas_validacion":null}]'::jsonb) on conflict (id) do nothing;
insert into public.forms (id, tenant_id, codigo, nombre, version, linea_id, activo, campos) values ('frm-hocol-mentoria', 'ten-hocol', 'F-MEN', 'Registro de mentoría / asistencia técnica', 1, 'line-hocol-l1', true, '[{"name":"tema","etiqueta_es":"Tema de la mentoría o asistencia","etiqueta_way":null,"tipo":"texto","obligatorio":true,"reglas_validacion":null},{"name":"fecha","etiqueta_es":"Fecha de la sesión","etiqueta_way":null,"tipo":"fecha","obligatorio":true,"reglas_validacion":null},{"name":"duracion_horas","etiqueta_es":"Duración (horas)","etiqueta_way":null,"tipo":"num","obligatorio":true,"reglas_validacion":null},{"name":"participantes","etiqueta_es":"Número de participantes","etiqueta_way":null,"tipo":"num","obligatorio":true,"reglas_validacion":null},{"name":"compromisos","etiqueta_es":"Compromisos acordados","etiqueta_way":null,"tipo":"texto","obligatorio":false,"reglas_validacion":null}]'::jsonb) on conflict (id) do nothing;

-- Verificación: debe devolver 3 tenants
select id, nombre from public.tenants order by id;
