-- ============================================================================
-- seed.sql — Configuración inicial de los tenants (GENERADO automáticamente
-- desde src/seeds/ por scripts/genSeedSql.mjs). No editar a mano.
-- Ejecutar en Supabase DESPUÉS de 001/002/003. Idempotente (on conflict do nothing).
-- ============================================================================


-- ===== Tenant: Guardianes del Mar Wayuu (ten-wayuu) =====
insert into public.tenants (id, nombre, financiador, entidad_ejecutora, unidad_analisis_default, moneda, vigencia_inicio, vigencia_fin, estado, config) values ('ten-wayuu', 'Guardianes del Mar Wayuu', 'Cooperación / Fondos propios', 'Fundación Guajira Competitiva', 'comunidad', 'COP', '2026-06-01', '2027-04-01', 'activo', '{"roles_nombres":{"gestor":"Gestor Comunitario","coordinador":"Coordinador","director":"Director del Proyecto","admin_fin":"Profesional Administrativo y Financiero","admin_tenant":"Administrador del Proyecto","financiador":"Financiador (consulta)","auditor":"Auditor (consulta)"},"pqrs_niveles":[{"nivel":"verde","sla_horas":72,"responsables":["gestor"],"descripcion":"Informativa / inconformidad aislada"},{"nivel":"amarillo","sla_horas":48,"responsables":["coordinador"],"descripcion":"Inconformidad recurrente / tensión localizada"},{"nivel":"naranja","sla_horas":24,"responsables":["coordinador","director"],"descripcion":"Conflicto activo / riesgo de bloqueo"},{"nivel":"rojo","sla_horas":0,"responsables":["director","coordinador"],"descripcion":"Riesgo a vida/integridad, VBG, bloqueo crítico (atención inmediata)"}],"idiomas":["es","way"],"consentimiento":{"finalidad":"Caracterización socioeconómica y seguimiento del proyecto Guardianes del Mar Wayuu, conforme a la Ley 1581 de 2012.","medios":["fisico","digital","verbal_testificado"]}}'::jsonb) on conflict (id) do nothing;
-- program_lines (1)
insert into public.program_lines (id, tenant_id, codigo, nombre, tipo, orden, fases) values ('line-wayuu-general', 'ten-wayuu', 'LG', 'Línea General de Ejecución', 'estructurada', 1, '[{"orden":1,"nombre":"Diagnóstico y caracterización"},{"orden":2,"nombre":"Dotación y fortalecimiento"},{"orden":3,"nombre":"Validación comercial y sostenibilidad"}]'::jsonb) on conflict (id) do nothing;
-- units (2)
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-wayuu-mayapo', 'ten-wayuu', 'Mayapo', 'manaure', 'legalizada', NULL, '{"lat":11.6919,"lng":-72.7592}'::jsonb, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-wayuu-elpajaro', 'ten-wayuu', 'El Pájaro', 'manaure', 'legalizada', NULL, '{"lat":11.7318,"lng":-72.6412}'::jsonb, NULL, '{}'::jsonb) on conflict (id) do nothing;
-- projects (1)
insert into public.projects (id, tenant_id, name, description, linea_id, unidad_ids, tipo, presupuesto, start_date, end_date, status) values ('proj-wayuu-001', 'ten-wayuu', 'Guardianes del Mar Wayuu', 'Fortalecimiento pesquero artesanal y desarrollo de experiencias turísticas comunitarias sostenibles en Mayapo y El Pájaro, Manaure, La Guajira.', 'line-wayuu-general', '["unit-wayuu-mayapo","unit-wayuu-elpajaro"]'::jsonb, 'comunitario', NULL, '2026-06-01', '2027-04-01', 'active') on conflict (id) do nothing;
-- logframes (11)
insert into public.logframes (id, tenant_id, project_id, type, code, description, parent_id) values ('lf-wayuu-impact', 'ten-wayuu', 'proj-wayuu-001', 'impact', 'OBJ-G', 'Mejorar de forma sostenible las condiciones socioeconómicas, la gobernanza comunitaria y la resiliencia climática de las comunidades pesqueras artesanales Wayuu en La Guajira.', NULL) on conflict (id) do nothing;
insert into public.logframes (id, tenant_id, project_id, type, code, description, parent_id) values ('lf-wayuu-out1', 'ten-wayuu', 'proj-wayuu-001', 'outcome', 'R-1', 'Fortalecimiento de la gobernanza asociativa y las capacidades organizacionales para la auto-gestión del territorio costero.', 'lf-wayuu-impact') on conflict (id) do nothing;
insert into public.logframes (id, tenant_id, project_id, type, code, description, parent_id) values ('lf-wayuu-out2', 'ten-wayuu', 'proj-wayuu-001', 'outcome', 'R-2', 'Mejoramiento de las capacidades productivas, cadena de frío y seguridad marítima de las tripulaciones.', 'lf-wayuu-impact') on conflict (id) do nothing;
insert into public.logframes (id, tenant_id, project_id, type, code, description, parent_id) values ('lf-wayuu-out3', 'ten-wayuu', 'proj-wayuu-001', 'outcome', 'R-3', 'Estructuración y validación del portafolio comunitario de pescaturismo y patrimonio cultural.', 'lf-wayuu-impact') on conflict (id) do nothing;
insert into public.logframes (id, tenant_id, project_id, type, code, description, parent_id) values ('lf-wayuu-out4', 'ten-wayuu', 'proj-wayuu-001', 'outcome', 'R-4', 'Establecimiento de acuerdos comerciales estables y mecanismos de financiamiento para la sostenibilidad.', 'lf-wayuu-impact') on conflict (id) do nothing;
insert into public.logframes (id, tenant_id, project_id, type, code, description, parent_id) values ('lf-wayuu-outp1.1', 'ten-wayuu', 'proj-wayuu-001', 'output', 'P-1.1', 'Diagnóstico base completado y talleres de gobernanza impartidos a líderes tradicionales.', 'lf-wayuu-out1') on conflict (id) do nothing;
insert into public.logframes (id, tenant_id, project_id, type, code, description, parent_id) values ('lf-wayuu-outp2.1', 'ten-wayuu', 'proj-wayuu-001', 'output', 'P-2.1', 'Activos estratégicos (cavas de frío, chalecos de seguridad, GPS náuticos) entregados a cooperativas.', 'lf-wayuu-out2') on conflict (id) do nothing;
insert into public.logframes (id, tenant_id, project_id, type, code, description, parent_id) values ('lf-wayuu-act1.1', 'ten-wayuu', 'proj-wayuu-001', 'activity', 'A-1.1', 'Socialización y concertación territorial del censo en Wayuunaiki con autoridades tradicionales.', 'lf-wayuu-outp1.1') on conflict (id) do nothing;
insert into public.logframes (id, tenant_id, project_id, type, code, description, parent_id) values ('lf-wayuu-act1.2', 'ten-wayuu', 'proj-wayuu-001', 'activity', 'A-1.2', 'Campaña de caracterización socioeconómica individual de pescadores artesanales en campo.', 'lf-wayuu-outp1.1') on conflict (id) do nothing;
insert into public.logframes (id, tenant_id, project_id, type, code, description, parent_id) values ('lf-wayuu-act2.1', 'ten-wayuu', 'proj-wayuu-001', 'activity', 'A-2.1', 'Entrega técnica de activos de conservación y cavas isotérmicas.', 'lf-wayuu-outp2.1') on conflict (id) do nothing;
insert into public.logframes (id, tenant_id, project_id, type, code, description, parent_id) values ('lf-wayuu-act2.2', 'ten-wayuu', 'proj-wayuu-001', 'activity', 'A-2.2', 'Talleres de capacitación en cartografía náutica y primeros auxilios marítimos.', 'lf-wayuu-outp2.1') on conflict (id) do nothing;
-- indicators (4)
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-wayuu-101', 'ten-wayuu', 'proj-wayuu-001', 'lf-wayuu-out1', 'line-wayuu-general', 'IND-1.1', 'Personas que culminan los ciclos de formación en turismo, inocuidad y pesca', 'Participantes', 0, 100, 15, 'numero', 'mensual', 'Registros de asistencia y certificados de formación', '{"fuente":{"formulario_id":"frm-wayuu-104"},"operacion":"suma","campo":"numero_asistentes"}'::jsonb, 0, false, false, '{"gender":{"male":10,"female":5,"other":0},"age":{"children":0,"youth":3,"adult":10,"elder":2},"ethnicity":{"indigenous":12,"afrodescendant":0,"local":3},"location":{"Mayapo":10,"ElPajaro":5}}'::jsonb) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-wayuu-102', 'ten-wayuu', 'proj-wayuu-001', 'lf-wayuu-out1', 'line-wayuu-general', 'IND-1.2', 'Asociaciones de pescadores fortalecidas en gobernanza comunitaria y administración', 'Asociaciones', 0, 5, 2, 'numero', 'trimestral', 'Actas de talleres y planes de fortalecimiento firmados', NULL, 0, false, false, '{"gender":{"male":0,"female":0,"other":0},"age":{"children":0,"youth":0,"adult":0,"elder":0},"ethnicity":{"indigenous":2,"afrodescendant":0,"local":0},"location":{"Mayapo":1,"ElPajaro":1}}'::jsonb) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-wayuu-201', 'ten-wayuu', 'proj-wayuu-001', 'lf-wayuu-out2', 'line-wayuu-general', 'IND-2.1', 'Asociaciones pesqueras dotadas de activos productivos de conservación y seguridad marítima', 'Asociaciones', 0, 2, 0, 'numero', 'semestral', 'Actas de entrega de activos con registro fotográfico', '{"fuente":{"formulario_id":"frm-wayuu-105"},"operacion":"conteo"}'::jsonb, 0, false, false, '{"gender":{"male":0,"female":0,"other":0},"age":{"children":0,"youth":0,"adult":0,"elder":0},"ethnicity":{"indigenous":0,"afrodescendant":0,"local":0},"location":{"Mayapo":0,"ElPajaro":0}}'::jsonb) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-wayuu-301', 'ten-wayuu', 'proj-wayuu-001', 'lf-wayuu-out3', 'line-wayuu-general', 'IND-3.1', 'Propuestas de experiencias turísticas comunitarias estructuradas y costeadas', 'Propuestas', 0, 5, 1, 'numero', 'trimestral', 'Documentos de propuesta con costeo validado', NULL, 0, false, false, '{"gender":{"male":0,"female":0,"other":0},"age":{"children":0,"youth":0,"adult":0,"elder":0},"ethnicity":{"indigenous":1,"afrodescendant":0,"local":0},"location":{"Mayapo":1,"ElPajaro":0}}'::jsonb) on conflict (id) do nothing;
-- forms (5)
insert into public.forms (id, tenant_id, codigo, nombre, version, linea_id, activo, campos) values ('frm-wayuu-103', 'ten-wayuu', 'FRM-103', 'Evaluación de Pitch Vivencial (Uso exclusivo Comité)', 1, 'line-wayuu-general', true, '[{"name":"asociacion_evaluada","etiqueta_es":"Asociación que presenta el Pitch","etiqueta_way":null,"tipo":"select","obligatorio":true,"reglas_validacion":null,"opciones":["Asociación de Mayapo A","Asociación de Mayapo B","Asociación de El Pájaro A","Otra"]},{"name":"puntaje_asistencia","etiqueta_es":"Puntaje Asistencia a Formación (Máx 30%)","etiqueta_way":null,"tipo":"num","obligatorio":true,"reglas_validacion":{"min":0,"max":30}},{"name":"puntaje_viabilidad","etiqueta_es":"Puntaje Viabilidad Técnica y Financiera (Máx 20%)","etiqueta_way":null,"tipo":"num","obligatorio":true,"reglas_validacion":{"min":0,"max":20}},{"name":"puntaje_pitch","etiqueta_es":"Puntaje Sustentación y Apropiación (Máx 20%)","etiqueta_way":null,"tipo":"num","obligatorio":true,"reglas_validacion":{"min":0,"max":20}},{"name":"puntaje_innovacion_cultural","etiqueta_es":"Puntaje Innovación y Enfoque Étnico (Máx 15%)","etiqueta_way":null,"tipo":"num","obligatorio":true,"reglas_validacion":{"min":0,"max":15}},{"name":"puntaje_inclusion_diferencial","etiqueta_es":"Puntaje Inclusión Social - Mujeres/Jóvenes (Máx 15%)","etiqueta_way":null,"tipo":"num","obligatorio":true,"reglas_validacion":{"min":0,"max":15}},{"name":"comentarios_jurado","etiqueta_es":"Justificación del Comité Evaluador","etiqueta_way":null,"tipo":"texto","obligatorio":true,"reglas_validacion":null}]'::jsonb) on conflict (id) do nothing;
insert into public.forms (id, tenant_id, codigo, nombre, version, linea_id, activo, campos) values ('frm-wayuu-104', 'ten-wayuu', 'FRM-104', 'Registro de Asistencia a Ciclos de Formación', 1, 'line-wayuu-general', true, '[{"name":"fecha_capacitacion","etiqueta_es":"Fecha de la sesión","etiqueta_way":null,"tipo":"fecha","obligatorio":true,"reglas_validacion":null},{"name":"modulo_dictado","etiqueta_es":"Módulo Temático","etiqueta_way":null,"tipo":"select","obligatorio":true,"reglas_validacion":null,"opciones":["Turismo Comunitario","Atención al Cliente","Manipulación de Alimentos","Seguridad Marítima DIMAR","Gobernanza y Sostenibilidad"]},{"name":"entidad_formadora","etiqueta_es":"Entidad Formadora","etiqueta_way":null,"tipo":"select","obligatorio":true,"reglas_validacion":null,"opciones":["SENA","Cámara de Comercio de La Guajira","Fundación Guajira Competitiva"]},{"name":"numero_asistentes","etiqueta_es":"Número total de asistentes en la sesión","etiqueta_way":null,"tipo":"num","obligatorio":true,"reglas_validacion":{"min":0}},{"name":"evidencia_fotografica","etiqueta_es":"Registro fotográfico / Planilla firmada","etiqueta_way":null,"tipo":"documento","obligatorio":true,"reglas_validacion":null}]'::jsonb) on conflict (id) do nothing;
insert into public.forms (id, tenant_id, codigo, nombre, version, linea_id, activo, campos) values ('frm-wayuu-105', 'ten-wayuu', 'FRM-105', 'Acta de Entrega de Activos Productivos y HSE', 1, 'line-wayuu-general', true, '[{"name":"fecha_entrega","etiqueta_es":"Fecha de entrega","etiqueta_way":null,"tipo":"fecha","obligatorio":true,"reglas_validacion":null},{"name":"asociacion_receptora","etiqueta_es":"Asociación Beneficiaria","etiqueta_way":null,"tipo":"select","obligatorio":true,"reglas_validacion":null,"opciones":["Asociación Ganadora Mayapo","Asociación Ganadora El Pájaro"]},{"name":"tipo_activo","etiqueta_es":"Categoría de los activos entregados","etiqueta_way":null,"tipo":"checklist","obligatorio":true,"reglas_validacion":null,"opciones":["Cavas isotérmicas (Cadena de frío)","Chalecos salvavidas","Equipos GPS/Radio","Herramientas de manejo postcaptura"]},{"name":"estado_entrega","etiqueta_es":"Estado de los equipos","etiqueta_way":null,"tipo":"select","obligatorio":true,"reglas_validacion":null,"opciones":["Nuevos y funcionales","Requieren instalación técnica","Con novedades (Describir abajo)"]},{"name":"nombre_representante","etiqueta_es":"Nombre del representante legal que recibe","etiqueta_way":null,"tipo":"texto","obligatorio":true,"reglas_validacion":null},{"name":"firma_representante","etiqueta_es":"Firma digital del representante que recibe","etiqueta_way":null,"tipo":"firma","obligatorio":true,"reglas_validacion":null},{"name":"acta_adjunta","etiqueta_es":"Acta firmada (PDF)","etiqueta_way":null,"tipo":"documento","obligatorio":true,"reglas_validacion":null}]'::jsonb) on conflict (id) do nothing;
insert into public.forms (id, tenant_id, codigo, nombre, version, linea_id, activo, campos) values ('frm-wayuu-106', 'ten-wayuu', 'FRM-106', 'Adopción de Mecanismos de Gobernanza y Sostenibilidad', 1, 'line-wayuu-general', true, '[{"name":"asociacion","etiqueta_es":"Organización Comunitaria","etiqueta_way":null,"tipo":"select","obligatorio":true,"reglas_validacion":null,"opciones":["Asociación Mayapo","Asociación El Pájaro"]},{"name":"tipo_mecanismo","etiqueta_es":"Tipo de mecanismo adoptado","etiqueta_way":null,"tipo":"select","obligatorio":true,"reglas_validacion":null,"opciones":["Fondo comunitario de ahorro","Reglamento interno de administración de activos","Plan de sostenibilidad financiera","Acuerdo de distribución de responsabilidades"]},{"name":"porcentaje_ahorro","etiqueta_es":"Porcentaje de ingresos destinado a reinversión (si aplica)","etiqueta_way":null,"tipo":"num","obligatorio":false,"reglas_validacion":{"min":0,"max":100}},{"name":"descripcion_acuerdo","etiqueta_es":"Resumen del acuerdo alcanzado","etiqueta_way":null,"tipo":"texto","obligatorio":true,"reglas_validacion":null},{"name":"documento_soporte","etiqueta_es":"Reglamento o acta de asamblea comunitaria (PDF)","etiqueta_way":null,"tipo":"documento","obligatorio":true,"reglas_validacion":null}]'::jsonb) on conflict (id) do nothing;
insert into public.forms (id, tenant_id, codigo, nombre, version, linea_id, activo, campos) values ('frm-wayuu-107', 'ten-wayuu', 'FRM-107', 'Registro de Alianzas Comerciales B2B', 1, 'line-wayuu-general', true, '[{"name":"fecha_firma","etiqueta_es":"Fecha de formalización del acuerdo","etiqueta_way":null,"tipo":"fecha","obligatorio":true,"reglas_validacion":null},{"name":"nombre_operador_aliado","etiqueta_es":"Nombre de la Agencia / Operador Turístico Aliado","etiqueta_way":null,"tipo":"texto","obligatorio":true,"reglas_validacion":null},{"name":"ruta_comercializada","etiqueta_es":"Experiencia vinculada","etiqueta_way":null,"tipo":"select","obligatorio":true,"reglas_validacion":null,"opciones":["Experiencia Mayapo","Experiencia El Pájaro","Ambas rutas"]},{"name":"tipo_acuerdo","etiqueta_es":"Naturaleza del acuerdo comercial","etiqueta_way":null,"tipo":"select","obligatorio":true,"reglas_validacion":null,"opciones":["Acuerdo de tarifas netas fijas","Inclusión en portafolio promocional","Contrato de exclusividad operativa","Carta de intención de compra"]},{"name":"responsabilidades_aliado","etiqueta_es":"Compromisos principales del aliado","etiqueta_way":null,"tipo":"texto","obligatorio":true,"reglas_validacion":null},{"name":"documento_soporte","etiqueta_es":"Acuerdo o carta de intención (PDF)","etiqueta_way":null,"tipo":"documento","obligatorio":true,"reglas_validacion":null}]'::jsonb) on conflict (id) do nothing;
-- surveys (2)
insert into public.surveys (id, tenant_id, title, description, indicator_id, schema, created_by) values ('srv-wayuu-101', 'ten-wayuu', 'Ficha de Caracterización y Diagnóstico Socioeconómico (Mes 1)', 'Formulario de caracterización socioeconómica para el censo de pescadores en Mayapo y El Pájaro.', 'ind-wayuu-101', '{"fields":[{"name":"full_name","label":"Nombre Completo del Pescador","type":"text","required":true},{"name":"genero","label":"Género","type":"select","options":["Masculino","Femenino","Otro"],"required":true},{"name":"edad","label":"Edad","type":"number","required":true},{"name":"clan","label":"Clan Wayuu de pertenencia (ej. Pushaina, Uriana, Epinayu)","type":"text","required":true},{"name":"location","label":"Corregimiento / Comunidad de Residencia","type":"select","options":["Mayapo","El Pájaro","Ranchería Aledaña Mayapo","Ranchería Aledaña El Pájaro"],"required":true},{"name":"association","label":"Asociación de Pescadores a la que pertenece","type":"select","options":["Asociación de Mayapo A","Asociación de Mayapo B","Asociación de El Pájaro A","Independiente / No asociado"],"required":true},{"name":"family_count","label":"Miembros dependientes en el núcleo familiar","type":"number","required":true},{"name":"fishing_only","label":"¿Es la pesca artesanal su única fuente de ingresos?","type":"select","options":["Sí, dependemos 100% de la pesca","No, alternamos con pastoreo/artesanías","No, alternamos con mototaxismo o comercio"],"required":true},{"name":"boat_motor","label":"¿Cuenta con embarcación y motor propio en buen estado?","type":"select","options":["Embarcación y motor propios operativos","Embarcación propia pero sin motor","No tiene activos propios (pesca de orilla)","Usa activos alquilados/prestados"],"required":true},{"name":"experiencia_turismo","label":"¿Ha prestado servicios turísticos antes?","type":"select","options":["Sí, recurrentemente","Sí, ocasionalmente","No, nunca"],"required":true},{"name":"equipos_seguridad_actuales","label":"Equipos de seguridad marítima con los que cuenta actualmente","type":"checklist","options":["Chalecos salvavidas","Radio de comunicación","GPS náutico","Botiquín","Ninguno"],"required":true},{"name":"comments","label":"Observaciones generales del diagnóstico","type":"textarea","required":false}]}'::jsonb, 'coordinacion@guajiracompetitiva.org') on conflict (id) do nothing;
insert into public.surveys (id, tenant_id, title, description, indicator_id, schema, created_by) values ('srv-wayuu-102', 'ten-wayuu', 'Evaluación del FAM TRIP y Satisfacción Comercial (Metas 9.6)', 'Encuesta técnica para evaluar la viabilidad de las experiencias piloto de pescaturismo.', 'ind-wayuu-301', '{"fields":[{"name":"agency_name","label":"Agencia de Viajes / Operadora Turística evaluadora","type":"text","required":true},{"name":"route_evaluated","label":"Experiencia Turística Evaluada","type":"select","options":["Pesca Ancestral Wayuu en Mayapo","Ruta de la Tortuga y Gastronomía en El Pájaro"],"required":true},{"name":"cultural_respect_checklist","label":"Elementos de pertinencia cultural evidenciados","type":"checklist","options":["Uso del idioma Wayuunaiki en la guianza","Interacción directa con autoridades tradicionales","Inclusión de relatos y saberes ancestrales","Consumo de gastronomía tradicional"],"required":true},{"name":"safety_equipment","label":"¿Se constató el uso riguroso de equipos de seguridad?","type":"select","options":["Sí, se cumplieron todos los protocolos DIMAR","Parcialmente (faltaban elementos)","No contaban con seguridad adecuada"],"required":true},{"name":"commercial_potential","label":"Potencial de inserción comercial (Modelo B2B)","type":"select","options":["Alto potencial","Medio potencial","Bajo potencial"],"required":true},{"name":"intencion_compra","label":"¿Estaría dispuesto a incluir esta ruta en el portafolio formal de su agencia?","type":"select","options":["Sí, de manera inmediata","Sí, si realizan ajustes técnicos/tarifarios","No por el momento"],"required":true},{"name":"improvement_points","label":"Recomendaciones de mejora identificadas","type":"textarea","required":false}]}'::jsonb, 'coordinacion@guajiracompetitiva.org') on conflict (id) do nothing;
-- feedbacks (2)
insert into public.feedbacks (id, tenant_id, project_id, unidad_id, category, canal, nivel, details, contact_info, is_confidential, estado, status, severity, response_text, created_at) values ('fb-wayuu-101', 'ten-wayuu', 'proj-wayuu-001', 'unit-wayuu-mayapo', 'complaint', 'presencial', 'amarillo', 'Pescadores de la zona norte de Mayapo reportan que la marea alta ha socavado los postes de amarre y solicitan priorizar el estudio de geolocalización de puntos de embarque.', 'Líder Gelasio Uriana, Cel: 312-445588', false, 'recibida', 'pending', 'medium', NULL, '2026-06-25T10:00:00.000Z') on conflict (id) do nothing;
insert into public.feedbacks (id, tenant_id, project_id, unidad_id, category, canal, nivel, details, contact_info, is_confidential, estado, status, severity, response_text, created_at) values ('fb-wayuu-102', 'ten-wayuu', 'proj-wayuu-001', 'unit-wayuu-elpajaro', 'complaint', 'anonimo', 'naranja', 'Reporte confidencial: Se detectaron sospechas de favoritismo familiar en la pre-asignación del kit de cavas de frío en la ranchería de El Pájaro.', 'Pescador anónimo de El Pájaro', true, 'clasificada', 'under_review', 'high', NULL, '2026-06-26T09:00:00.000Z') on conflict (id) do nothing;
-- lessons_learned (1)
insert into public.lessons_learned (id, tenant_id, project_id, title, description, challenges, recommendations, action_plan) values ('ll-wayuu-101', 'ten-wayuu', 'proj-wayuu-001', 'Estandarización de tarifas netas para el canal B2B', 'Durante la operación piloto de la Ruta Ancestral Jemeilli, se evidenció que las agencias mayoristas exigen tarifas netas fijas anualizadas con comisiones del 20% y seguros de accidentes.', 'Las asociaciones comunitarias cambiaban los costos de los almuerzos semanalmente según el precio de mercado, rompiendo reservas de agencias.', 'Establecer acuerdos de costos fijos estacionales por semestre con las asociaciones y contratar pólizas colectivas anuales.', '{"description":"Redactar acuerdo firmado de tarifas fijas para almuerzos con la cooperativa de Mayapo.","responsible":"Coordinador Territorial MEAL","deadline":"2026-07-15","status":"pending"}'::jsonb) on conflict (id) do nothing;

-- ===== Tenant: Implementación Reforma Laboral — Clínica Maicao (ten-maicao) =====
insert into public.tenants (id, nombre, financiador, entidad_ejecutora, unidad_analisis_default, moneda, vigencia_inicio, vigencia_fin, estado, config) values ('ten-maicao', 'Implementación Reforma Laboral — Clínica Maicao', 'Clínica Maicao S.A.S.', 'Fundación Guajira Competitiva', 'organizacion', 'COP', '2026-03-30', '2026-09-30', 'activo', '{"roles_nombres":{"gestor":"Consultor de Campo","coordinador":"Coordinador","director":"Director del Proyecto","admin_fin":"Profesional Administrativo y Financiero","admin_tenant":"Administrador del Proyecto","financiador":"Financiador (consulta)","auditor":"Auditor (consulta)"},"pqrs_niveles":[{"nivel":"verde","sla_horas":72,"responsables":["gestor"],"descripcion":"Informativa / inconformidad aislada"},{"nivel":"amarillo","sla_horas":48,"responsables":["coordinador"],"descripcion":"Inconformidad recurrente / tensión localizada"},{"nivel":"naranja","sla_horas":24,"responsables":["coordinador","director"],"descripcion":"Conflicto activo / riesgo de bloqueo"},{"nivel":"rojo","sla_horas":0,"responsables":["director","coordinador"],"descripcion":"Riesgo a vida/integridad, VBG, bloqueo crítico (atención inmediata)"}],"idiomas":["es"],"consentimiento":{"finalidad":"Diagnóstico organizacional y evaluación de riesgo psicosocial del personal de la Clínica Maicao, conforme a la Ley 1581 de 2012.","medios":["fisico","digital"]}}'::jsonb) on conflict (id) do nothing;
-- program_lines (1)
insert into public.program_lines (id, tenant_id, codigo, nombre, tipo, orden, fases) values ('line-maicao-general', 'ten-maicao', 'LG', 'Línea General de Consultoría', 'estructurada', 1, '[{"orden":1,"nombre":"Diagnóstico jurídico y organizacional"},{"orden":2,"nombre":"Adecuación e implementación"},{"orden":3,"nombre":"Apropiación y cierre"}]'::jsonb) on conflict (id) do nothing;
-- units (1)
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-maicao-clinica', 'ten-maicao', 'Clínica Maicao — Sede Principal', 'maicao', 'legalizada', NULL, '{"lat":11.3778,"lng":-72.2394}'::jsonb, 150, '{"tipo_organizacion":"IPS de alta complejidad"}'::jsonb) on conflict (id) do nothing;
-- projects (1)
insert into public.projects (id, tenant_id, name, description, linea_id, unidad_ids, tipo, presupuesto, start_date, end_date, status) values ('proj-maicao-002', 'ten-maicao', 'Implementación Reforma Laboral - Clínica Maicao', 'Diseño, adecuación e implementación del modelo laboral organizacional de la Clínica Maicao en el marco de la Ley 2466 de 2025 (Reforma Laboral), mitigando riesgos jurídicos y optimizando mallas de turnos de salud de alta complejidad.', 'line-maicao-general', '["unit-maicao-clinica"]'::jsonb, 'consultoria', NULL, '2026-03-30', '2026-09-30', 'active') on conflict (id) do nothing;
-- logframes (13)
insert into public.logframes (id, tenant_id, project_id, type, code, description, parent_id) values ('lf-maicao-impact', 'ten-maicao', 'proj-maicao-002', 'impact', 'OBJ-G', 'Garantizar la adecuada implementación de la Reforma Laboral (Ley 2466 de 2025) en la Clínica Maicao mediante un modelo de transformación organizacional 360° para mitigar riesgos legales y optimizar la continuidad del servicio de salud.', NULL) on conflict (id) do nothing;
insert into public.logframes (id, tenant_id, project_id, type, code, description, parent_id) values ('lf-maicao-out1', 'ten-maicao', 'proj-maicao-002', 'outcome', 'R-1', 'Adecuación normativa, prevención de riesgo jurídico y fortalecimiento del marco legal institucional.', 'lf-maicao-impact') on conflict (id) do nothing;
insert into public.logframes (id, tenant_id, project_id, type, code, description, parent_id) values ('lf-maicao-out2', 'ten-maicao', 'proj-maicao-002', 'outcome', 'R-2', 'Optimización de la estructura de jornada laboral, turnos, mallas, liquidación de nómina y recargos.', 'lf-maicao-impact') on conflict (id) do nothing;
insert into public.logframes (id, tenant_id, project_id, type, code, description, parent_id) values ('lf-maicao-out3', 'ten-maicao', 'proj-maicao-002', 'outcome', 'R-3', 'Fortalecimiento del clima laboral, prevención de conflictos y cumplimiento de obligaciones en riesgo psicosocial.', 'lf-maicao-impact') on conflict (id) do nothing;
insert into public.logframes (id, tenant_id, project_id, type, code, description, parent_id) values ('lf-maicao-out4', 'ten-maicao', 'proj-maicao-002', 'outcome', 'R-4', 'Apropiación institucional y capacitación del talento humano sobre los cambios derivados de la reforma laboral.', 'lf-maicao-impact') on conflict (id) do nothing;
insert into public.logframes (id, tenant_id, project_id, type, code, description, parent_id) values ('lf-maicao-otp1.1', 'ten-maicao', 'proj-maicao-002', 'output', 'P-1.1', 'Políticas de contratación y modelos contractuales adaptados y redactados.', 'lf-maicao-out1') on conflict (id) do nothing;
insert into public.logframes (id, tenant_id, project_id, type, code, description, parent_id) values ('lf-maicao-otp2.1', 'ten-maicao', 'proj-maicao-002', 'output', 'P-2.1', 'Manual de jornada laboral adaptado a 42 horas y mallas de turnos de salud optimizadas.', 'lf-maicao-out2') on conflict (id) do nothing;
insert into public.logframes (id, tenant_id, project_id, type, code, description, parent_id) values ('lf-maicao-otp3.1', 'ten-maicao', 'proj-maicao-002', 'output', 'P-3.1', 'Protocolo de prevención del acoso laboral y diagnóstico psicosocial.', 'lf-maicao-out3') on conflict (id) do nothing;
insert into public.logframes (id, tenant_id, project_id, type, code, description, parent_id) values ('lf-maicao-otp4.1', 'ten-maicao', 'proj-maicao-002', 'output', 'P-4.1', 'Talleres presenciales de formación ejecutados y kit pedagógico institucional de reforma.', 'lf-maicao-out4') on conflict (id) do nothing;
insert into public.logframes (id, tenant_id, project_id, type, code, description, parent_id) values ('lf-maicao-act1.1', 'ten-maicao', 'proj-maicao-002', 'activity', 'A-1.1', 'Elaboración del informe diagnóstico jurídico de la Clínica y matriz de riesgos inicial.', 'lf-maicao-otp1.1') on conflict (id) do nothing;
insert into public.logframes (id, tenant_id, project_id, type, code, description, parent_id) values ('lf-maicao-act2.1', 'ten-maicao', 'proj-maicao-002', 'activity', 'A-2.1', 'Ejecución de simulaciones financieras sobre el impacto de recargos nocturnos y dominicales.', 'lf-maicao-otp2.1') on conflict (id) do nothing;
insert into public.logframes (id, tenant_id, project_id, type, code, description, parent_id) values ('lf-maicao-act3.1', 'ten-maicao', 'proj-maicao-002', 'activity', 'A-3.1', 'Aplicación de encuestas de evaluación del riesgo psicosocial del personal médico y administrativo.', 'lf-maicao-otp3.1') on conflict (id) do nothing;
insert into public.logframes (id, tenant_id, project_id, type, code, description, parent_id) values ('lf-maicao-act4.1', 'ten-maicao', 'proj-maicao-002', 'activity', 'A-4.1', 'Diseño e impartición de talleres de gestión del cambio para coordinadores y jefes de área.', 'lf-maicao-otp4.1') on conflict (id) do nothing;
-- indicators (4)
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-maicao-101', 'ten-maicao', 'proj-maicao-002', 'lf-maicao-out1', 'line-maicao-general', 'IND-1.1', 'Porcentaje de adecuación jurídica de contratos del personal', '%', 0, 100, 0, 'porcentaje', 'mensual', 'Matriz de contratos revisados y adendas firmadas', NULL, 0, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-maicao-201', 'ten-maicao', 'proj-maicao-002', 'lf-maicao-out2', 'line-maicao-general', 'IND-2.1', 'Simulaciones financieras de nómina y turnos completadas y aprobadas', 'Simulaciones', 0, 3, 0, 'numero', 'trimestral', 'Informes de simulación aprobados por gerencia', NULL, 0, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-maicao-301', 'ten-maicao', 'proj-maicao-002', 'lf-maicao-out3', 'line-maicao-general', 'IND-3.1', 'Protocolo contra el acoso laboral socializado y aprobado', 'Protocolo', 0, 1, 0, 'numero', 'final', 'Acta de aprobación del comité de convivencia', NULL, 0, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-maicao-401', 'ten-maicao', 'proj-maicao-002', 'lf-maicao-out4', 'line-maicao-general', 'IND-4.1', 'Colaboradores de la clínica capacitados en gestión del cambio', 'Colaboradores', 0, 150, 0, 'numero', 'mensual', 'Listados de asistencia a talleres con firma', NULL, 0, false, false, NULL) on conflict (id) do nothing;

-- ===== Tenant: Convenio Asociación Guajira (Ecopetrol–Hocol) 2026 (ten-hocol) =====
insert into public.tenants (id, nombre, financiador, entidad_ejecutora, unidad_analisis_default, moneda, vigencia_inicio, vigencia_fin, estado, config) values ('ten-hocol', 'Convenio Asociación Guajira (Ecopetrol–Hocol) 2026', 'Hocol S.A.', 'Fundación Guajira Competitiva', 'comunidad', 'COP', '2026-01-01', '2027-04-30', 'activo', '{"roles_nombres":{"gestor":"Gestor Comunitario Wayuu","coordinador":"Coordinador Territorial","director":"Director del Proyecto","admin_fin":"Profesional Administrativo y Financiero","admin_tenant":"Administrador de Tenant","financiador":"Hocol S.A. (consulta)","auditor":"Auditor (consulta)"},"pqrs_niveles":[{"nivel":"verde","sla_horas":72,"responsables":["gestor"],"descripcion":"Informativa / inconformidad aislada"},{"nivel":"amarillo","sla_horas":48,"responsables":["coordinador"],"descripcion":"Inconformidad recurrente / tensión localizada"},{"nivel":"naranja","sla_horas":24,"responsables":["coordinador","director"],"descripcion":"Conflicto activo / riesgo de bloqueo"},{"nivel":"rojo","sla_horas":0,"responsables":["director","coordinador"],"descripcion":"Riesgo a vida/integridad, VBG, bloqueo crítico (atención inmediata)"}],"idiomas":["es","way"],"consentimiento":{"finalidad":"Registro y seguimiento de beneficiarios del convenio de inversión social Asociación Guajira (Ecopetrol–Hocol), con enfoque étnico y conforme a la Ley 1581 de 2012. Los datos se usan exclusivamente para los fines del convenio.","medios":["fisico","digital","verbal_testificado"]}}'::jsonb) on conflict (id) do nothing;
-- program_lines (6)
insert into public.program_lines (id, tenant_id, codigo, nombre, tipo, orden, fases) values ('line-hocol-l1', 'ten-hocol', 'L1', 'L1 — Fortalecimiento comunitario', 'estructurada', 1, '[{"orden":1,"nombre":"Diagnóstico"},{"orden":2,"nombre":"Caracterización"},{"orden":3,"nombre":"Plan de fortalecimiento"},{"orden":4,"nombre":"Formulación de proyectos"},{"orden":5,"nombre":"Implementación y planes de inversión"},{"orden":6,"nombre":"Sostenibilidad"}]'::jsonb) on conflict (id) do nothing;
insert into public.program_lines (id, tenant_id, codigo, nombre, tipo, orden, fases) values ('line-hocol-l2', 'ten-hocol', 'L2', 'L2 — Atención de solicitudes', 'flexible', 2, '[]'::jsonb) on conflict (id) do nothing;
insert into public.program_lines (id, tenant_id, codigo, nombre, tipo, orden, fases) values ('line-hocol-l3', 'ten-hocol', 'L3', 'L3 — Cultura y patrimonio', 'flexible', 3, '[]'::jsonb) on conflict (id) do nothing;
insert into public.program_lines (id, tenant_id, codigo, nombre, tipo, orden, fases) values ('line-hocol-l4', 'ten-hocol', 'L4', 'L4 — Apoyos humanitarios y usos y costumbres', 'flexible', 4, '[]'::jsonb) on conflict (id) do nothing;
insert into public.program_lines (id, tenant_id, codigo, nombre, tipo, orden, fases) values ('line-hocol-l5', 'ten-hocol', 'L5', 'L5 — Salud', 'flexible', 5, '[]'::jsonb) on conflict (id) do nothing;
insert into public.program_lines (id, tenant_id, codigo, nombre, tipo, orden, fases) values ('line-hocol-meal', 'ten-hocol', 'MEAL', 'Eje transversal MEAL', 'transversal', 6, '[]'::jsonb) on conflict (id) do nothing;
-- units (36)
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-01', 'ten-hocol', 'Comunidad Wayuu 01 — Riohacha (nombre por confirmar en onboarding)', 'riohacha', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-02', 'ten-hocol', 'Comunidad Wayuu 02 — Riohacha (nombre por confirmar en onboarding)', 'riohacha', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-03', 'ten-hocol', 'Comunidad Wayuu 03 — Riohacha (nombre por confirmar en onboarding)', 'riohacha', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-04', 'ten-hocol', 'Comunidad Wayuu 04 — Riohacha (nombre por confirmar en onboarding)', 'riohacha', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-05', 'ten-hocol', 'Comunidad Wayuu 05 — Riohacha (nombre por confirmar en onboarding)', 'riohacha', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-06', 'ten-hocol', 'Comunidad Wayuu 06 — Riohacha (nombre por confirmar en onboarding)', 'riohacha', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-07', 'ten-hocol', 'Comunidad Wayuu 07 — Riohacha (nombre por confirmar en onboarding)', 'riohacha', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-08', 'ten-hocol', 'Comunidad Wayuu 08 — Riohacha (nombre por confirmar en onboarding)', 'riohacha', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-09', 'ten-hocol', 'Comunidad Wayuu 09 — Riohacha (nombre por confirmar en onboarding)', 'riohacha', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-10', 'ten-hocol', 'Comunidad Wayuu 10 — Riohacha (nombre por confirmar en onboarding)', 'riohacha', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-11', 'ten-hocol', 'Comunidad Wayuu 11 — Riohacha (nombre por confirmar en onboarding)', 'riohacha', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-12', 'ten-hocol', 'Comunidad Wayuu 12 — Riohacha (nombre por confirmar en onboarding)', 'riohacha', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-13', 'ten-hocol', 'Comunidad Wayuu 13 — Riohacha (nombre por confirmar en onboarding)', 'riohacha', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-14', 'ten-hocol', 'Comunidad Wayuu 14 — Riohacha (nombre por confirmar en onboarding)', 'riohacha', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-15', 'ten-hocol', 'Comunidad Wayuu 15 — Riohacha (nombre por confirmar en onboarding)', 'riohacha', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-16', 'ten-hocol', 'Comunidad Wayuu 16 — Riohacha (nombre por confirmar en onboarding)', 'riohacha', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-17', 'ten-hocol', 'Comunidad Wayuu 17 — Riohacha (nombre por confirmar en onboarding)', 'riohacha', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-18', 'ten-hocol', 'Comunidad Wayuu 18 — Riohacha (nombre por confirmar en onboarding)', 'riohacha', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-19', 'ten-hocol', 'Comunidad Wayuu 19 — Manaure (nombre por confirmar en onboarding)', 'manaure', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-20', 'ten-hocol', 'Comunidad Wayuu 20 — Manaure (nombre por confirmar en onboarding)', 'manaure', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-21', 'ten-hocol', 'Comunidad Wayuu 21 — Manaure (nombre por confirmar en onboarding)', 'manaure', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-22', 'ten-hocol', 'Comunidad Wayuu 22 — Manaure (nombre por confirmar en onboarding)', 'manaure', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-23', 'ten-hocol', 'Comunidad Wayuu 23 — Manaure (nombre por confirmar en onboarding)', 'manaure', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-24', 'ten-hocol', 'Comunidad Wayuu 24 — Manaure (nombre por confirmar en onboarding)', 'manaure', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-25', 'ten-hocol', 'Comunidad Wayuu 25 — Manaure (nombre por confirmar en onboarding)', 'manaure', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-26', 'ten-hocol', 'Comunidad Wayuu 26 — Manaure (nombre por confirmar en onboarding)', 'manaure', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-27', 'ten-hocol', 'Comunidad Wayuu 27 — Manaure (nombre por confirmar en onboarding)', 'manaure', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-28', 'ten-hocol', 'Comunidad Wayuu 28 — Manaure (nombre por confirmar en onboarding)', 'manaure', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-29', 'ten-hocol', 'Comunidad Wayuu 29 — Manaure (nombre por confirmar en onboarding)', 'manaure', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-30', 'ten-hocol', 'Comunidad Wayuu 30 — Manaure (nombre por confirmar en onboarding)', 'manaure', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-31', 'ten-hocol', 'Comunidad Wayuu 31 — Manaure (nombre por confirmar en onboarding)', 'manaure', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-32', 'ten-hocol', 'Comunidad Wayuu 32 — Manaure (nombre por confirmar en onboarding)', 'manaure', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-33', 'ten-hocol', 'Comunidad Wayuu 33 — Manaure (nombre por confirmar en onboarding)', 'manaure', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-34', 'ten-hocol', 'Comunidad Wayuu 34 — Manaure (nombre por confirmar en onboarding)', 'manaure', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-35', 'ten-hocol', 'Comunidad Wayuu 35 — Manaure (nombre por confirmar en onboarding)', 'manaure', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
insert into public.units (id, tenant_id, nombre, municipio, estado_reconocimiento, autoridad_tradicional, geopunto, poblacion_estimada, atributos) values ('unit-hocol-36', 'ten-hocol', 'Comunidad Wayuu 36 — Manaure (nombre por confirmar en onboarding)', 'manaure', 'en_proceso', NULL, NULL, NULL, '{}'::jsonb) on conflict (id) do nothing;
-- indicators (44)
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-001', 'ten-hocol', NULL, NULL, NULL, 'IND-EST-01', 'Comunidades fortalecidas', 'Comunidades', NULL, 36, 0, 'numero', 'final', 'Actas de cierre de fase por comunidad', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-002', 'ten-hocol', NULL, NULL, NULL, 'IND-EST-02', 'Proyectos comunitarios formulados', 'Proyectos', NULL, 36, 0, 'numero', 'trimestral', 'Documentos de proyecto formulados', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-003', 'ten-hocol', NULL, NULL, NULL, 'IND-EST-03', 'Proyectos comunitarios implementados', 'Proyectos', NULL, 36, 0, 'numero', 'trimestral', 'Actas de entrega e informes de implementación', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-004', 'ten-hocol', NULL, NULL, NULL, 'IND-EST-04', 'Cumplimiento físico del convenio', '%', NULL, 95, 0, 'porcentaje', 'mensual', 'Tablero de control — avance físico', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-005', 'ten-hocol', NULL, NULL, NULL, 'IND-EST-05', 'Ejecución financiera del convenio', '%', NULL, 95, 0, 'porcentaje', 'mensual', 'Informe financiero mensual', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-006', 'ten-hocol', NULL, NULL, NULL, 'IND-EST-06', 'Cumplimiento de cronograma', '%', NULL, 95, 0, 'porcentaje', 'mensual', 'Cronograma actualizado vs ejecutado', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-007', 'ten-hocol', NULL, NULL, NULL, 'IND-EST-07', 'Trazabilidad documental', '%', NULL, 100, 0, 'porcentaje', 'continua', 'Repositorio documental con evidencias enlazadas', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-008', 'ten-hocol', NULL, NULL, NULL, 'IND-EST-08', 'Satisfacción del financiador', '%', NULL, 90, 0, 'porcentaje', 'semestral', 'Encuesta de satisfacción Hocol', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-009', 'ten-hocol', NULL, NULL, 'line-hocol-l1', 'IND-L1-01', 'Diagnósticos comunitarios realizados', 'Diagnósticos', NULL, 36, 0, 'numero', 'mensual', 'Fichas de diagnóstico validadas', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-010', 'ten-hocol', NULL, NULL, 'line-hocol-l1', 'IND-L1-02', 'Comunidades caracterizadas', 'Comunidades', NULL, 36, 0, 'numero', 'mensual', 'Fichas de caracterización validadas', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-011', 'ten-hocol', NULL, NULL, 'line-hocol-l1', 'IND-L1-03', 'Planes de fortalecimiento elaborados', 'Planes', NULL, 36, 0, 'numero', 'trimestral', 'Planes de fortalecimiento aprobados', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-012', 'ten-hocol', NULL, NULL, 'line-hocol-l1', 'IND-L1-04', 'Proyectos formulados (L1)', 'Proyectos', NULL, 36, 0, 'numero', 'trimestral', 'Documentos de formulación', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-013', 'ten-hocol', NULL, NULL, 'line-hocol-l1', 'IND-L1-05', 'Proyectos implementados (L1)', 'Proyectos', NULL, 36, 0, 'numero', 'trimestral', 'Actas de implementación', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-014', 'ten-hocol', NULL, NULL, 'line-hocol-l1', 'IND-L1-06', 'Planes de inversión ejecutados', 'Planes', NULL, 36, 0, 'numero', 'trimestral', 'Soportes de ejecución de inversión', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-015', 'ten-hocol', NULL, NULL, 'line-hocol-l1', 'IND-L1-07', 'Culminación de procesos de formación', '%', NULL, 90, 0, 'porcentaje', 'trimestral', 'Registros de asistencia y certificados', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-016', 'ten-hocol', NULL, NULL, 'line-hocol-l1', 'IND-L1-08', 'Estrategia de sostenibilidad formulada', 'Documento', NULL, 1, 0, 'numero', 'final', 'Documento de estrategia aprobado', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-017', 'ten-hocol', NULL, NULL, 'line-hocol-l2', 'IND-L2-01', 'Solicitudes atendidas', 'Solicitudes', NULL, NULL, 0, 'numero', 'mensual', 'Registros de solicitud con cierre técnico', NULL, NULL, false, true, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-018', 'ten-hocol', NULL, NULL, 'line-hocol-l2', 'IND-L2-02', 'Solicitudes con cierre técnico', '%', NULL, 100, 0, 'porcentaje', 'mensual', 'Actas de cierre técnico', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-019', 'ten-hocol', NULL, NULL, 'line-hocol-l2', 'IND-L2-03', 'Solicitudes atendidas en tiempo', '%', NULL, 90, 0, 'porcentaje', 'mensual', 'Comparativo fecha solicitud vs atención', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-020', 'ten-hocol', NULL, NULL, 'line-hocol-l2', 'IND-L2-04', 'Trazabilidad de solicitudes', '%', NULL, 100, 0, 'porcentaje', 'continua', 'Expedientes con evidencias completas', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-021', 'ten-hocol', NULL, NULL, 'line-hocol-l3', 'IND-L3-01', 'Iniciativas culturales apoyadas', 'Iniciativas', NULL, NULL, 0, 'numero', 'trimestral', 'Registros de apoyo cultural', NULL, NULL, false, true, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-022', 'ten-hocol', NULL, NULL, 'line-hocol-l3', 'IND-L3-02', 'Actividades de patrimonio realizadas', 'Actividades', NULL, NULL, 0, 'numero', 'trimestral', 'Registros de actividad con evidencia', NULL, NULL, false, true, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-023', 'ten-hocol', NULL, NULL, 'line-hocol-l3', 'IND-L3-03', 'Participantes en actividades culturales', 'Personas', NULL, NULL, 0, 'numero', 'trimestral', 'Registros de asistencia', NULL, NULL, false, true, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-024', 'ten-hocol', NULL, NULL, 'line-hocol-l3', 'IND-L3-04', 'Satisfacción con actividades culturales', '%', NULL, 90, 0, 'porcentaje', 'semestral', 'Encuestas de satisfacción', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-025', 'ten-hocol', NULL, NULL, 'line-hocol-l4', 'IND-L4-01', 'Apoyos humanitarios ejecutados', 'Apoyos', NULL, NULL, 0, 'numero', 'mensual', 'Registros de apoyo con acta de entrega', NULL, NULL, false, true, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-026', 'ten-hocol', NULL, NULL, 'line-hocol-l4', 'IND-L4-02', 'Atenciones de usos y costumbres', 'Atenciones', NULL, NULL, 0, 'numero', 'mensual', 'Registros de atención', NULL, NULL, false, true, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-027', 'ten-hocol', NULL, NULL, 'line-hocol-l4', 'IND-L4-03', 'Trazabilidad de apoyos (L4)', '%', NULL, 100, 0, 'porcentaje', 'continua', 'Expedientes con evidencias completas', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-028', 'ten-hocol', NULL, NULL, 'line-hocol-l4', 'IND-L4-04', 'Satisfacción con apoyos (L4)', '%', NULL, 90, 0, 'porcentaje', 'semestral', 'Encuestas de satisfacción', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-029', 'ten-hocol', NULL, NULL, 'line-hocol-l5', 'IND-L5-01', 'Jornadas y acciones de salud realizadas', 'Jornadas', NULL, NULL, 0, 'numero', 'mensual', 'Registros de atención en salud', NULL, NULL, false, true, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-030', 'ten-hocol', NULL, NULL, 'line-hocol-l5', 'IND-L5-02', 'Personas beneficiadas en salud', 'Personas', NULL, NULL, 0, 'numero', 'mensual', 'Registros de atención individual', NULL, NULL, false, true, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-031', 'ten-hocol', NULL, NULL, 'line-hocol-l5', 'IND-L5-03', 'Instituciones de salud articuladas', 'Instituciones', NULL, NULL, 0, 'numero', 'trimestral', 'Convenios/actas de articulación', NULL, NULL, false, true, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-032', 'ten-hocol', NULL, NULL, 'line-hocol-l5', 'IND-L5-04', 'Satisfacción con jornadas de salud', '%', NULL, 90, 0, 'porcentaje', 'semestral', 'Encuestas de satisfacción', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-033', 'ten-hocol', NULL, NULL, 'line-hocol-meal', 'IND-MEAL-01', 'Línea base consolidada', 'Documento', NULL, 1, 0, 'numero', 'final', 'Documento de línea base congelado', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-034', 'ten-hocol', NULL, NULL, 'line-hocol-meal', 'IND-MEAL-02', 'Sistema MEAL en operación', 'Sistema', NULL, 1, 0, 'numero', 'continua', 'Plataforma operativa con usuarios activos', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-035', 'ten-hocol', NULL, NULL, 'line-hocol-meal', 'IND-MEAL-03', 'Tablero de control actualizado mensualmente', '%', NULL, 100, 0, 'porcentaje', 'mensual', 'Bitácora de actualización del tablero', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-036', 'ten-hocol', NULL, NULL, 'line-hocol-meal', 'IND-MEAL-04', 'Indicadores actualizados al día', '%', NULL, 100, 0, 'porcentaje', 'mensual', 'Reporte de vigencia de indicadores', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-037', 'ten-hocol', NULL, NULL, 'line-hocol-meal', 'IND-MEAL-05', 'Informes técnicos mensuales entregados', 'Informes', NULL, 12, 0, 'numero', 'mensual', 'Informes técnicos radicados', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-038', 'ten-hocol', NULL, NULL, 'line-hocol-meal', 'IND-MEAL-06', 'Informes financieros mensuales entregados', 'Informes', NULL, 12, 0, 'numero', 'mensual', 'Informes financieros radicados', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-039', 'ten-hocol', NULL, NULL, 'line-hocol-meal', 'IND-MEAL-07', 'Informes de seguimiento entregados', 'Informes', NULL, 12, 0, 'numero', 'mensual', 'Informes de seguimiento radicados', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-040', 'ten-hocol', NULL, NULL, 'line-hocol-meal', 'IND-MEAL-08', 'Evaluación final realizada', 'Evaluación', NULL, 1, 0, 'numero', 'final', 'Informe de evaluación final', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-041', 'ten-hocol', NULL, NULL, 'line-hocol-meal', 'IND-MEAL-09', 'Evaluación de impacto realizada', 'Evaluación', NULL, 1, 0, 'numero', 'final', 'Informe de evaluación de impacto', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-042', 'ten-hocol', NULL, NULL, 'line-hocol-meal', 'IND-MEAL-10', 'Documento de lecciones aprendidas', 'Documento', NULL, 1, 0, 'numero', 'final', 'Documento consolidado de lecciones', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-043', 'ten-hocol', NULL, NULL, 'line-hocol-meal', 'IND-MEAL-11', 'Banco de evidencias consolidado', 'Repositorio', NULL, 1, 0, 'numero', 'continua', 'Repositorio documental completo', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
insert into public.indicators (id, tenant_id, project_id, logframe_id, linea_id, code, name, unit, baseline, target, actual, meta_tipo, frecuencia, medio_verificacion, formula, linea_base_valor, linea_base_congelada, meta_ajustable, disaggregated_data) values ('ind-hocol-044', 'ten-hocol', NULL, NULL, 'line-hocol-meal', 'IND-MEAL-12', 'Trazabilidad extremo a extremo', '%', NULL, 100, 0, 'porcentaje', 'continua', 'Auditoría de reconstrucción de indicadores', NULL, NULL, false, false, NULL) on conflict (id) do nothing;
-- forms (9)
insert into public.forms (id, tenant_id, codigo, nombre, version, linea_id, activo, campos) values ('frm-hocol-lineabase', 'ten-hocol', 'F-LB', 'Encuesta de línea base comunitaria', 1, 'line-hocol-l1', true, '[{"name":"comunidad_confirma","etiqueta_es":"Comunidad donde se aplica","etiqueta_way":null,"tipo":"texto","obligatorio":true,"reglas_validacion":null},{"name":"fecha_aplicacion","etiqueta_es":"Fecha de aplicación","etiqueta_way":null,"tipo":"fecha","obligatorio":true,"reglas_validacion":null},{"name":"geopunto","etiqueta_es":"Ubicación de la aplicación","etiqueta_way":null,"tipo":"geo","obligatorio":true,"reglas_validacion":null},{"name":"poblacion_total","etiqueta_es":"Población total estimada de la comunidad","etiqueta_way":null,"tipo":"num","obligatorio":true,"reglas_validacion":null},{"name":"familias","etiqueta_es":"Número de familias","etiqueta_way":null,"tipo":"num","obligatorio":true,"reglas_validacion":null},{"name":"acceso_agua","etiqueta_es":"¿La comunidad cuenta con acceso a agua?","etiqueta_way":null,"tipo":"bool","obligatorio":true,"reglas_validacion":null},{"name":"fuente_ingresos","etiqueta_es":"Principal fuente de ingresos","etiqueta_way":null,"tipo":"select","obligatorio":true,"reglas_validacion":null,"opciones":["Pastoreo","Artesanías","Pesca","Comercio","Jornaleo","Otra"]},{"name":"observaciones","etiqueta_es":"Observaciones generales","etiqueta_way":null,"tipo":"texto","obligatorio":false,"reglas_validacion":null}]'::jsonb) on conflict (id) do nothing;
insert into public.forms (id, tenant_id, codigo, nombre, version, linea_id, activo, campos) values ('frm-hocol-caracterizacion', 'ten-hocol', 'F-CAR', 'Ficha de caracterización comunitaria', 1, 'line-hocol-l1', true, '[{"name":"autoridad","etiqueta_es":"Autoridad tradicional de la comunidad","etiqueta_way":null,"tipo":"texto","obligatorio":true,"reglas_validacion":null},{"name":"estado_reconocimiento","etiqueta_es":"Estado de reconocimiento","etiqueta_way":null,"tipo":"select","obligatorio":true,"reglas_validacion":null,"opciones":["Legalizada","En proceso"]},{"name":"geopunto","etiqueta_es":"Coordenadas de la comunidad","etiqueta_way":null,"tipo":"geo","obligatorio":true,"reglas_validacion":null},{"name":"foto_panoramica","etiqueta_es":"Foto panorámica de la comunidad","etiqueta_way":null,"tipo":"foto","obligatorio":true,"reglas_validacion":null},{"name":"organizaciones","etiqueta_es":"Organizaciones presentes en la comunidad","etiqueta_way":null,"tipo":"texto","obligatorio":false,"reglas_validacion":null}]'::jsonb) on conflict (id) do nothing;
insert into public.forms (id, tenant_id, codigo, nombre, version, linea_id, activo, campos) values ('frm-hocol-asistencia', 'ten-hocol', 'F-ASI', 'Registro de asistencia', 1, 'line-hocol-l1', true, '[{"name":"actividad","etiqueta_es":"Nombre de la actividad","etiqueta_way":null,"tipo":"texto","obligatorio":true,"reglas_validacion":null},{"name":"fecha","etiqueta_es":"Fecha de la actividad","etiqueta_way":null,"tipo":"fecha","obligatorio":true,"reglas_validacion":null},{"name":"num_asistentes","etiqueta_es":"Número de asistentes","etiqueta_way":null,"tipo":"num","obligatorio":true,"reglas_validacion":null},{"name":"num_mujeres","etiqueta_es":"Número de mujeres asistentes","etiqueta_way":null,"tipo":"num","obligatorio":true,"reglas_validacion":null},{"name":"foto_asistencia","etiqueta_es":"Foto del listado de asistencia","etiqueta_way":null,"tipo":"foto","obligatorio":true,"reglas_validacion":null},{"name":"firma_responsable","etiqueta_es":"Firma del responsable","etiqueta_way":null,"tipo":"firma","obligatorio":true,"reglas_validacion":null}]'::jsonb) on conflict (id) do nothing;
insert into public.forms (id, tenant_id, codigo, nombre, version, linea_id, activo, campos) values ('frm-hocol-acta-entrega', 'ten-hocol', 'F-ACT', 'Acta de entrega', 1, 'line-hocol-l1', true, '[{"name":"bien_entregado","etiqueta_es":"Bien o servicio entregado","etiqueta_way":null,"tipo":"texto","obligatorio":true,"reglas_validacion":null},{"name":"receptor","etiqueta_es":"Persona/organización que recibe","etiqueta_way":null,"tipo":"texto","obligatorio":true,"reglas_validacion":null},{"name":"fecha_entrega","etiqueta_es":"Fecha de entrega","etiqueta_way":null,"tipo":"fecha","obligatorio":true,"reglas_validacion":null},{"name":"geopunto","etiqueta_es":"Lugar de la entrega","etiqueta_way":null,"tipo":"geo","obligatorio":true,"reglas_validacion":null},{"name":"foto_entrega","etiqueta_es":"Registro fotográfico de la entrega","etiqueta_way":null,"tipo":"foto","obligatorio":true,"reglas_validacion":null},{"name":"firma_receptor","etiqueta_es":"Firma de quien recibe","etiqueta_way":null,"tipo":"firma","obligatorio":true,"reglas_validacion":null}]'::jsonb) on conflict (id) do nothing;
insert into public.forms (id, tenant_id, codigo, nombre, version, linea_id, activo, campos) values ('frm-hocol-solicitud', 'ten-hocol', 'F-SOL', 'Registro de solicitud (L2)', 1, 'line-hocol-l2', true, '[{"name":"descripcion","etiqueta_es":"Descripción de la solicitud","etiqueta_way":null,"tipo":"texto","obligatorio":true,"reglas_validacion":null},{"name":"fecha_solicitud","etiqueta_es":"Fecha de la solicitud","etiqueta_way":null,"tipo":"fecha","obligatorio":true,"reglas_validacion":null},{"name":"solicitante","etiqueta_es":"Nombre del solicitante o autoridad","etiqueta_way":null,"tipo":"texto","obligatorio":true,"reglas_validacion":null},{"name":"priorizada","etiqueta_es":"¿Priorizada por el financiador?","etiqueta_way":null,"tipo":"bool","obligatorio":true,"reglas_validacion":null},{"name":"estado_atencion","etiqueta_es":"Estado de atención","etiqueta_way":null,"tipo":"select","obligatorio":true,"reglas_validacion":null,"opciones":["Registrada","En gestión","Atendida","Cerrada"]}]'::jsonb) on conflict (id) do nothing;
insert into public.forms (id, tenant_id, codigo, nombre, version, linea_id, activo, campos) values ('frm-hocol-apoyo-cultural', 'ten-hocol', 'F-CUL', 'Registro de apoyo cultural (L3)', 1, 'line-hocol-l3', true, '[{"name":"iniciativa","etiqueta_es":"Iniciativa o actividad cultural apoyada","etiqueta_way":null,"tipo":"texto","obligatorio":true,"reglas_validacion":null},{"name":"fecha","etiqueta_es":"Fecha de la actividad","etiqueta_way":null,"tipo":"fecha","obligatorio":true,"reglas_validacion":null},{"name":"participantes","etiqueta_es":"Número de participantes","etiqueta_way":null,"tipo":"num","obligatorio":true,"reglas_validacion":null},{"name":"foto_actividad","etiqueta_es":"Registro fotográfico","etiqueta_way":null,"tipo":"foto","obligatorio":true,"reglas_validacion":null},{"name":"satisfaccion","etiqueta_es":"Satisfacción de los participantes (1 a 5)","etiqueta_way":null,"tipo":"escala","obligatorio":true,"reglas_validacion":null}]'::jsonb) on conflict (id) do nothing;
insert into public.forms (id, tenant_id, codigo, nombre, version, linea_id, activo, campos) values ('frm-hocol-apoyo-humanitario', 'ten-hocol', 'F-HUM', 'Registro de apoyo humanitario (L4)', 1, 'line-hocol-l4', true, '[{"name":"tipo_apoyo","etiqueta_es":"Tipo de apoyo","etiqueta_way":null,"tipo":"select","obligatorio":true,"reglas_validacion":null,"opciones":["Humanitario","Usos y costumbres"]},{"name":"descripcion","etiqueta_es":"Descripción del apoyo entregado","etiqueta_way":null,"tipo":"texto","obligatorio":true,"reglas_validacion":null},{"name":"fecha_entrega","etiqueta_es":"Fecha de entrega","etiqueta_way":null,"tipo":"fecha","obligatorio":true,"reglas_validacion":null},{"name":"geopunto","etiqueta_es":"Lugar de entrega","etiqueta_way":null,"tipo":"geo","obligatorio":true,"reglas_validacion":null},{"name":"foto_entrega","etiqueta_es":"Registro fotográfico","etiqueta_way":null,"tipo":"foto","obligatorio":true,"reglas_validacion":null},{"name":"firma_receptor","etiqueta_es":"Firma de quien recibe","etiqueta_way":null,"tipo":"firma","obligatorio":true,"reglas_validacion":null}]'::jsonb) on conflict (id) do nothing;
insert into public.forms (id, tenant_id, codigo, nombre, version, linea_id, activo, campos) values ('frm-hocol-atencion-salud', 'ten-hocol', 'F-SAL', 'Registro de atención en salud (L5)', 1, 'line-hocol-l5', true, '[{"name":"tipo_jornada","etiqueta_es":"Tipo de jornada o acción de salud","etiqueta_way":null,"tipo":"texto","obligatorio":true,"reglas_validacion":null},{"name":"fecha","etiqueta_es":"Fecha de la jornada","etiqueta_way":null,"tipo":"fecha","obligatorio":true,"reglas_validacion":null},{"name":"personas_atendidas","etiqueta_es":"Personas atendidas","etiqueta_way":null,"tipo":"num","obligatorio":true,"reglas_validacion":null},{"name":"institucion","etiqueta_es":"Institución de salud articulada","etiqueta_way":null,"tipo":"texto","obligatorio":false,"reglas_validacion":null},{"name":"foto_jornada","etiqueta_es":"Registro fotográfico","etiqueta_way":null,"tipo":"foto","obligatorio":true,"reglas_validacion":null}]'::jsonb) on conflict (id) do nothing;
insert into public.forms (id, tenant_id, codigo, nombre, version, linea_id, activo, campos) values ('frm-hocol-mentoria', 'ten-hocol', 'F-MEN', 'Registro de mentoría / asistencia técnica', 1, 'line-hocol-l1', true, '[{"name":"tema","etiqueta_es":"Tema de la mentoría o asistencia","etiqueta_way":null,"tipo":"texto","obligatorio":true,"reglas_validacion":null},{"name":"fecha","etiqueta_es":"Fecha de la sesión","etiqueta_way":null,"tipo":"fecha","obligatorio":true,"reglas_validacion":null},{"name":"duracion_horas","etiqueta_es":"Duración (horas)","etiqueta_way":null,"tipo":"num","obligatorio":true,"reglas_validacion":null},{"name":"participantes","etiqueta_es":"Número de participantes","etiqueta_way":null,"tipo":"num","obligatorio":true,"reglas_validacion":null},{"name":"compromisos","etiqueta_es":"Compromisos acordados","etiqueta_way":null,"tipo":"texto","obligatorio":false,"reglas_validacion":null}]'::jsonb) on conflict (id) do nothing;

-- Verificación: debe devolver 3 tenants
select id, nombre from public.tenants order by id;
